/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import general.Sistema;
import java.awt.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.*;

/**
 *
 * @author axell
 */
public class FrmRegistrarTrabajador extends javax.swing.JFrame {
    private static boolean disponible = true;
    
    /**
     * Creates new form FrmRegistrarAlumno
     */
    
    public FrmRegistrarTrabajador() {
        
    }
    
    public void run(){
        initComponents();
        setVisible(true);
    }
    
    public static void setDisponible(boolean estado){
        disponible = estado;
    }
    
    
    public static boolean isDisponible(){
        return disponible;
    }
    
    public void cerrarForm(){
        this.dispose();
        setDisponible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        labelPrimerNombre = new javax.swing.JLabel();
        labelNombre2 = new javax.swing.JLabel();
        boxDepartamento1 = new javax.swing.JComboBox<>();
        labelApellidoPaterno = new javax.swing.JLabel();
        labelApellidoMaterno = new javax.swing.JLabel();
        labelTelefono = new javax.swing.JLabel();
        radioBtnM = new javax.swing.JRadioButton();
        radioBtnF = new javax.swing.JRadioButton();
        txtTelefono = new javax.swing.JTextField();
        labelGenero = new javax.swing.JLabel();
        boxDepartamento2 = new javax.swing.JComboBox<>();
        boxProvincia2 = new javax.swing.JComboBox<>();
        labelInformacionPrimaria = new javax.swing.JLabel();
        labelInformacionSecundaria = new javax.swing.JLabel();
        boxProvincia1 = new javax.swing.JComboBox<>();
        labelInfoNac = new javax.swing.JLabel();
        labelInfoRes = new javax.swing.JLabel();
        btnRegistro = new javax.swing.JButton();
        labelInfoLogin = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        labelRellenarIP = new javax.swing.JLabel();
        labelFechaNac = new javax.swing.JLabel();
        fecha = new com.toedter.calendar.JDateChooser();
        labelRellenarIS = new javax.swing.JLabel();
        labelApellidoMaterno1 = new javax.swing.JLabel();
        txtAdminpass = new javax.swing.JPasswordField();
        labelBoolUser = new javax.swing.JLabel();
        labelBoolPassword = new javax.swing.JLabel();
        labelBoolCorreo = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtNombre1 = new javax.swing.JTextField();
        txtNombre2 = new javax.swing.JTextField();
        txtUser = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtPassword2 = new javax.swing.JPasswordField();
        txtEmail = new javax.swing.JTextField();
        txtApellido1 = new javax.swing.JTextField();
        txtApellido2 = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        labelRellenarIL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(79, 79, 79));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        labelTitulo.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        labelTitulo.setText("REGISTRAR TRABAJADOR");

        labelPrimerNombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelPrimerNombre.setText("PRIMER NOMBRE");

        labelNombre2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelNombre2.setText("SEGUNDO NOMBRE");

        boxDepartamento1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        labelApellidoPaterno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelApellidoPaterno.setText("APELLIDO PATERNO");

        labelApellidoMaterno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelApellidoMaterno.setText("APELLIDO MATERNO");

        labelTelefono.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelTelefono.setText("TELÉFONO");

        radioBtnM.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        radioBtnM.setText("MASCULINO");
        radioBtnM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnMActionPerformed(evt);
            }
        });

        radioBtnF.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        radioBtnF.setText("FEMENINO");

        txtTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelefonoFocusLost(evt);
            }
        });

        labelGenero.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelGenero.setText("GÉNERO");

        boxDepartamento2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        boxProvincia2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        labelInformacionPrimaria.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        labelInformacionPrimaria.setText("INFORMACIÓN PRIMARIA");

        labelInformacionSecundaria.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        labelInformacionSecundaria.setText("INFORMACIÓN SECUNDARIA");

        boxProvincia1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        boxProvincia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxProvincia1ActionPerformed(evt);
            }
        });

        labelInfoNac.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelInfoNac.setText("INFORMACIÓN DE NACIMIENTO");

        labelInfoRes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelInfoRes.setText("INFORMACIÓN DE RESIDENCIA");

        btnRegistro.setBackground(new java.awt.Color(27, 120, 206));
        btnRegistro.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnRegistro.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistro.setText("REGISTRAR");
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });

        labelInfoLogin.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        labelInfoLogin.setText("INFORMACIÓN DE INICIO DE SESIÓN");

        labelRellenarIP.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        labelRellenarIP.setForeground(new java.awt.Color(240, 28, 49));
        labelRellenarIP.setText("                                             ");

        labelFechaNac.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelFechaNac.setText("FECHA DE NACIMIENTO");

        fecha.setDateFormatString("dd/MM/yyyy");
        fecha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        labelRellenarIS.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        labelRellenarIS.setForeground(new java.awt.Color(240, 28, 49));
        labelRellenarIS.setText("                                             ");

        labelApellidoMaterno1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelApellidoMaterno1.setText("DOC. IDENTIDAD");

        txtAdminpass.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        txtAdminpass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAdminpassFocusLost(evt);
            }
        });

        labelBoolUser.setFont(new java.awt.Font("Arial", 3, 10)); // NOI18N
        labelBoolUser.setForeground(new java.awt.Color(240, 28, 49));
        labelBoolUser.setText("                                             ");

        labelBoolPassword.setFont(new java.awt.Font("Arial", 3, 10)); // NOI18N
        labelBoolPassword.setForeground(new java.awt.Color(240, 28, 49));
        labelBoolPassword.setText("                                             ");

        labelBoolCorreo.setFont(new java.awt.Font("Arial", 3, 10)); // NOI18N
        labelBoolCorreo.setForeground(new java.awt.Color(240, 28, 49));
        labelBoolCorreo.setText("                                             ");

        txtNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre1ActionPerformed(evt);
            }
        });

        txtUser.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        txtUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUserFocusLost(evt);
            }
        });

        txtPassword.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });

        txtPassword2.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        txtPassword2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPassword2FocusLost(evt);
            }
        });

        txtEmail.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });

        txtDNI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDNIFocusLost(evt);
            }
        });

        labelRellenarIL.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        labelRellenarIL.setForeground(new java.awt.Color(240, 28, 49));
        labelRellenarIL.setText("                                             ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(91, 91, 91)
                            .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(labelInfoLogin, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelInfoNac)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(boxProvincia1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(boxDepartamento1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(50, 50, 50)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelInfoRes)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(boxProvincia2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(boxDepartamento2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(labelInformacionSecundaria, javax.swing.GroupLayout.Alignment.LEADING))
                            .addContainerGap(150, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelTelefono)
                                .addGap(18, 18, 18)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(labelGenero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioBtnM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioBtnF))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(323, 323, 323)
                                .addComponent(labelRellenarIS))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelNombre2)
                                    .addComponent(labelPrimerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombre1)
                                    .addComponent(txtNombre2, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelApellidoMaterno)
                                            .addComponent(labelApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelApellidoMaterno1))
                                        .addGap(9, 9, 9))
                                    .addComponent(labelFechaNac, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtApellido1, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                            .addComponent(txtApellido2)
                                            .addComponent(txtDNI)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAdminpass, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelBoolPassword)
                                    .addComponent(labelBoolCorreo)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(labelInformacionPrimaria)
                                    .addGap(173, 173, 173)
                                    .addComponent(labelRellenarIP))
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelBoolUser))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(324, 324, 324)
                                .addComponent(labelRellenarIL)))
                        .addGap(0, 138, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRellenarIP)
                    .addComponent(labelInformacionPrimaria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrimerNombre)
                    .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre2)
                    .addComponent(txtNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelApellidoPaterno)
                    .addComponent(txtApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelApellidoMaterno)
                    .addComponent(txtApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelApellidoMaterno1)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFechaNac)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelInformacionSecundaria)
                    .addComponent(labelRellenarIS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTelefono)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioBtnM)
                    .addComponent(radioBtnF))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelInfoRes)
                    .addComponent(labelInfoNac))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxDepartamento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxDepartamento2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxProvincia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxProvincia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelInfoLogin)
                    .addComponent(labelRellenarIL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBoolUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBoolPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(txtAdminpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelBoolCorreo)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(btnRegistro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void radioBtnMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBtnMActionPerformed

    private void boxProvincia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxProvincia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxProvincia1ActionPerformed

    private void txtTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefonoFocusLost
        // TODO add your handling code here:
        String telefono = txtTelefono.getText();
        boolean valido = Sistema.validarTextoNumerico(telefono, 9);
        if(!valido)
            txtTelefono.setForeground(Color.RED);
        
        else
            txtTelefono.setForeground(Color.BLACK);
            
    }//GEN-LAST:event_txtTelefonoFocusLost

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void txtNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre1ActionPerformed

    private void txtDNIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDNIFocusLost
        // TODO add your handling code here:
        String DNI = txtDNI.getText();
        boolean valido = Sistema.validarTextoNumerico(DNI, 8);
        if(!valido)
            txtDNI.setForeground(Color.RED);
        
        else
            txtDNI.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtDNIFocusLost

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        // TODO add your handling code here:
        String email = txtEmail.getText();
        boolean valido = Sistema.validarCorreo(email);
        if(!valido && !txtEmail.getText().equals("")){
            txtEmail.setForeground(Color.RED);
            labelBoolCorreo.setText("INGRESE UN CORREO VALIDO");
        }
            
        
        else{
            txtEmail.setForeground(Color.BLACK);
            labelBoolCorreo.setText(null);
        }
            
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusLost
        // TODO add your handling code here:
        if(!Sistema.validarUserName(txtUser.getText())){
            txtUser.setForeground(Color.RED);
            labelBoolUser.setText("EL USUARIO YA SE ENCUENTRA EN USO");
        }
            
        else{
            txtUser.setForeground(Color.BLACK);
            labelBoolUser.setText(null);
        }
            
    }//GEN-LAST:event_txtUserFocusLost

    private void txtPassword2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassword2FocusLost
        // TODO add your handling code here:
        if(!txtPassword.getText().equals(txtPassword2.getText())){
            txtPassword.setForeground(Color.RED);
            txtPassword2.setForeground(Color.RED);
            labelBoolPassword.setText("LAS CONTRASEÑAS NO COINCIDEN");
        }    
        else{
            txtPassword.setForeground(Color.BLACK);
            txtPassword2.setForeground(Color.BLACK);
            labelBoolPassword.setText(null);
        }
            
    }//GEN-LAST:event_txtPassword2FocusLost

    private void txtAdminpassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAdminpassFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtAdminpassFocusLost

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        // TODO add your handling code here:
        txtPassword.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtPasswordFocusLost

    /**
     * @param args the command line arguments
     */
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegistrarTrabajador().setVisible(true);
            }
        });
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> boxDepartamento1;
    public javax.swing.JComboBox<String> boxDepartamento2;
    public javax.swing.JComboBox<String> boxProvincia1;
    public javax.swing.JComboBox<String> boxProvincia2;
    public javax.swing.JButton btnRegistro;
    public com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel labelApellidoMaterno;
    private javax.swing.JLabel labelApellidoMaterno1;
    private javax.swing.JLabel labelApellidoPaterno;
    public javax.swing.JLabel labelBoolCorreo;
    public javax.swing.JLabel labelBoolPassword;
    public javax.swing.JLabel labelBoolUser;
    private javax.swing.JLabel labelFechaNac;
    private javax.swing.JLabel labelGenero;
    private javax.swing.JLabel labelInfoLogin;
    private javax.swing.JLabel labelInfoNac;
    private javax.swing.JLabel labelInfoRes;
    private javax.swing.JLabel labelInformacionPrimaria;
    private javax.swing.JLabel labelInformacionSecundaria;
    private javax.swing.JLabel labelNombre2;
    private javax.swing.JLabel labelPrimerNombre;
    public javax.swing.JLabel labelRellenarIL;
    public javax.swing.JLabel labelRellenarIP;
    public javax.swing.JLabel labelRellenarIS;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel labelTitulo;
    public javax.swing.JRadioButton radioBtnF;
    public javax.swing.JRadioButton radioBtnM;
    public javax.swing.JPasswordField txtAdminpass;
    public javax.swing.JTextField txtApellido1;
    public javax.swing.JTextField txtApellido2;
    public javax.swing.JTextField txtDNI;
    public javax.swing.JTextField txtEmail;
    public javax.swing.JTextField txtNombre1;
    public javax.swing.JTextField txtNombre2;
    public javax.swing.JPasswordField txtPassword;
    public javax.swing.JPasswordField txtPassword2;
    public javax.swing.JTextField txtTelefono;
    public javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

 
}
