/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.*;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author axell
 */
public class FrmSistema extends javax.swing.JFrame {
    /*DefaultTableModel modeloTabla;
    JFileChooser archivo = new JFileChooser(System.getProperty("user.dir"));
    private void cargar(){
        try{
            String texto = "";
            Object [] cabeceras = {"N", "Codigo", "Nombre", "Apellido", "Carrera"};
            modeloTabla = new DefaultTableModel(cabeceras, 0);
            archivo.showOpenDialog(this);
            File abrir = archivo.getSelectedFile();
            
            Object [] elemento = new Object[5];
            
            if(abrir != null){
                FileReader fichero = new FileReader(abrir);
                BufferedReader leer = new BufferedReader(fichero);
                while((texto = leer.readLine()) != null){
                    String registro[] = texto.split(";");
                    elemento[0] = registro[0];
                    elemento[1] = registro[1];
                    elemento[2] = registro[2];
                    elemento[3] = registro[3];
                    elemento[4] = registro[4];
                    modeloTabla.addRow(elemento);
                }
                jTable1.setModel(modeloTabla);
            }
        }    
        catch(IOException e){
            System.out.println("Error: " + e);
        }
    }*/
    
    /**
     * Creates new form FrmSistema
     */
    public FrmSistema() {
        
        
        //funcionalidadBotones();
    }
    
    public void run(){
        initComponents();
        setVisible(true);
    }
    
    /*public void funcionalidadBotones(){
        btnCargar.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                /*AbreLista obj = new AbreLista();
                panelCenter.add(obj);
                obj.setVisible(true);
                
            }
            
        });
            
        
    }*/
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel4 = new javax.swing.JPanel();
        bvalidar = new javax.swing.JButton();
        arrastartysoltar = new javax.swing.JTextField();
        btnCargar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelCenter = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblInformación = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtUsuarioConectado = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtError = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnUnlogin = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        bgeexcel = new javax.swing.JButton();
        BtnOpenexcel = new javax.swing.JButton();
        bgreporte = new javax.swing.JButton();
        bgetxt = new javax.swing.JButton();
        btnValidarCorreos = new javax.swing.JButton();
        btnInformaciónIngresantes = new javax.swing.JButton();
        menuBarra = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setPreferredSize(new java.awt.Dimension(300, 367));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        bvalidar.setBackground(new java.awt.Color(79, 79, 79));
        bvalidar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bvalidar.setForeground(new java.awt.Color(255, 255, 255));
        bvalidar.setText("Validar CSV");
        bvalidar.setPreferredSize(new java.awt.Dimension(87, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 161;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(46, 10, 111, 20);
        jPanel4.add(bvalidar, gridBagConstraints);

        arrastartysoltar.setEditable(false);
        arrastartysoltar.setBackground(new java.awt.Color(255, 255, 255));
        arrastartysoltar.setForeground(new java.awt.Color(255, 255, 255));
        arrastartysoltar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        arrastartysoltar.setPreferredSize(new java.awt.Dimension(6, 25));
        arrastartysoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrastartysoltarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 264;
        gridBagConstraints.ipady = 132;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 10, 0, 20);
        jPanel4.add(arrastartysoltar, gridBagConstraints);

        btnCargar.setBackground(new java.awt.Color(79, 79, 79));
        btnCargar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCargar.setForeground(new java.awt.Color(255, 255, 255));
        btnCargar.setText("Buscar archivo");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 143;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 10, 0, 20);
        jPanel4.add(btnCargar, gridBagConstraints);

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_START);

        jPanel1.setBackground(new java.awt.Color(63, 172, 255));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GENERADOR DE CORREOS Y CÓDIGOS - UNMSM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(731, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        panelCenter.setBackground(new java.awt.Color(87, 87, 87));

        jScrollPane2.setHorizontalScrollBar(null);

        tblInformación.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        tblInformación.setForeground(new java.awt.Color(51, 51, 51));
        tblInformación.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                " ", " ", " "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblInformación.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblInformación.setGridColor(new java.awt.Color(255, 255, 255));
        tblInformación.setSelectionBackground(new java.awt.Color(153, 153, 153));
        tblInformación.setShowVerticalLines(false);
        tblInformación.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblInformación);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/formulario.png"))); // NOI18N

        txtUsuarioConectado.setEditable(false);
        txtUsuarioConectado.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtUsuarioConectado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuarioConectado.setToolTipText("");
        txtUsuarioConectado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioConectadoActionPerformed(evt);
            }
        });

        txtError.setEditable(false);
        txtError.setBackground(new java.awt.Color(102, 102, 102));
        txtError.setColumns(2);
        txtError.setForeground(new java.awt.Color(255, 255, 255));
        txtError.setLineWrap(true);
        txtError.setRows(8);
        txtError.setTabSize(5);
        jScrollPane1.setViewportView(txtError);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("INFORME DE ERRORES");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("REPORTE DE REGISTROS");

        btnUnlogin.setBackground(new java.awt.Color(79, 79, 79));
        btnUnlogin.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnUnlogin.setForeground(new java.awt.Color(255, 255, 255));
        btnUnlogin.setText("CERRAR SESIÓN");

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        bgeexcel.setBackground(new java.awt.Color(27, 120, 206));
        bgeexcel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bgeexcel.setForeground(new java.awt.Color(255, 255, 255));
        bgeexcel.setText("GENERAR EXCEL");

        BtnOpenexcel.setBackground(new java.awt.Color(27, 120, 206));
        BtnOpenexcel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnOpenexcel.setForeground(new java.awt.Color(255, 255, 255));
        BtnOpenexcel.setText("ABRIR EXCEL");
        BtnOpenexcel.setToolTipText("");
        BtnOpenexcel.setPreferredSize(new java.awt.Dimension(173, 25));
        BtnOpenexcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOpenexcelActionPerformed(evt);
            }
        });

        bgreporte.setBackground(new java.awt.Color(27, 120, 206));
        bgreporte.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bgreporte.setForeground(new java.awt.Color(255, 255, 255));
        bgreporte.setText("REPORTE");
        bgreporte.setPreferredSize(new java.awt.Dimension(173, 25));
        bgreporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgreporteActionPerformed(evt);
            }
        });

        bgetxt.setBackground(new java.awt.Color(27, 120, 206));
        bgetxt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bgetxt.setForeground(new java.awt.Color(255, 255, 255));
        bgetxt.setText("GENERAR TXT");
        bgetxt.setPreferredSize(new java.awt.Dimension(173, 25));

        btnValidarCorreos.setBackground(new java.awt.Color(27, 120, 206));
        btnValidarCorreos.setForeground(new java.awt.Color(255, 255, 255));
        btnValidarCorreos.setText("VALIDAR ENVÍO DE CORREOS");

        btnInformaciónIngresantes.setBackground(new java.awt.Color(79, 79, 79));
        btnInformaciónIngresantes.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnInformaciónIngresantes.setForeground(new java.awt.Color(255, 255, 255));
        btnInformaciónIngresantes.setText("CONSULTAR INFORMACIÓN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnOpenexcel, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bgeexcel, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bgreporte, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bgetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(btnValidarCorreos, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnInformaciónIngresantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bgetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bgeexcel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnValidarCorreos))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bgreporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnOpenexcel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(btnInformaciónIngresantes, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout panelCenterLayout = new javax.swing.GroupLayout(panelCenter);
        panelCenter.setLayout(panelCenterLayout);
        panelCenterLayout.setHorizontalGroup(
            panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCenterLayout.createSequentialGroup()
                        .addGroup(panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelCenterLayout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUsuarioConectado, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(203, 203, 203)
                        .addComponent(btnUnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );
        panelCenterLayout.setVerticalGroup(
            panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCenterLayout.createSequentialGroup()
                .addGroup(panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(panelCenterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsuarioConectado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(panelCenter, java.awt.BorderLayout.CENTER);
        setJMenuBar(menuBarra);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargarActionPerformed

    private void arrastartysoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrastartysoltarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arrastartysoltarActionPerformed

    private void bgreporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bgreporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bgreporteActionPerformed

    private void txtUsuarioConectadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioConectadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioConectadoActionPerformed

    private void BtnOpenexcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOpenexcelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnOpenexcelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnOpenexcel;
    public javax.swing.JTextField arrastartysoltar;
    public javax.swing.JButton bgeexcel;
    public javax.swing.JButton bgetxt;
    public javax.swing.JButton bgreporte;
    public javax.swing.JButton btnCargar;
    public javax.swing.JButton btnInformaciónIngresantes;
    public javax.swing.JButton btnUnlogin;
    public javax.swing.JButton btnValidarCorreos;
    public javax.swing.JButton bvalidar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JMenuBar menuBarra;
    public javax.swing.JPanel panelCenter;
    public javax.swing.JTable tblInformación;
    public javax.swing.JTextArea txtError;
    public javax.swing.JTextField txtUsuarioConectado;
    // End of variables declaration//GEN-END:variables

    

}
